changelog:
  exclude:
    labels:
      - ignore-for-release
      - chore
  categories:
    - title: "✨ New Features & Improvements"
      labels:
        - enhancement
        - feature
        - improvement
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "🔒 Security"
      labels:
        - security
    - title: "📦 Dependencies"
      labels:
        - dependencies
        - deps
    - title: "📖 Documentation"
      labels:
        - documentation
    - title: "🔧 Maintenance"
      labels:
        - "*"
