export const IPC = {
  VaultExists: "vault:exists",
  VaultCreate: "vault:create",
  VaultOpen: "vault:open",
  VaultLock: "vault:lock",
  VaultListProfiles: "vault:listProfiles",
  VaultUpsertProfile: "vault:upsertProfile",
  VaultRemoveProfile: "vault:removeProfile",
  VaultDuplicateProfile: "vault:duplicateProfile",
  K8sContexts: "k8s:contexts",
  K8sNamespaces: "k8s:namespaces",
  K8sPods: "k8s:pods",
  K8sServices: "k8s:services",
  K8sSecrets: "k8s:secrets",
  K8sSecretKeys: "k8s:secretKeys",
  DockerContainers: "docker:containers",
  DockerContainerEnvs: "docker:containerEnvs",
  ListDatabases: "mirror:listDatabases",
  ListDatabasesFromProfile: "mirror:listDatabasesFromProfile",
  Diff: "mirror:diff",
  DiffProgress: "mirror:diff:progress",
  Apply: "mirror:apply",
  ApplyProgress: "mirror:apply:progress",
  Overwrite: "mirror:overwrite",
  DumpToFile: "dump:toFile",
  DumpProgress: "dump:progress",
  DefaultVaultPath: "paths:defaultVault",
  UpdateAvailable:        "update:available",
  UpdateDownloadProgress: "update:downloadProgress",
  UpdateDownloaded:       "update:downloaded",
  UpdateError:            "update:error",
  InstallUpdate:          "update:install",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
